title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

<<<<<<< HEAD
url: https://alixtrot.github.io/blog/
=======
url:
>>>>>>> master
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

<<<<<<< HEAD
markdown: redcarpet
highlighter: pygments
=======
markdown: kramdown
highlighter: rouge
>>>>>>> master
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
