title: Alix Trot
description: Keeping pace with data and technology for social good

url: https://alixtrot.github.io/blog/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: alixtrot
   twitter: alixtrot
   email: alix@trot.io
