title: alix trot
description: Keeping the pace with data and technology for social good

url:
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: alixtrot
   twitter: alixtrot
   email: alix@trot.io

google_analytics: "UA-58263416-1"
